name: blog-paesa-es

services:
  ghost:
    image: ghost:5.19.3
    environment:
      - database__client=sqlite3
      - database__connection__filename=content/data/ghost.db
      - database__useNullAsDefault=true
      - database__debug=false
      - logging__level=error
      - logging__transports=["stdout"]
    networks:
      default: null
    ports:
      - mode: ingress
        target: 2368
        published: "2368"
        protocol: tcp
    volumes:
      - type: volume
        source: data
        target: /var/lib/ghost/content
        volume: {}

networks:
  default:
    name: blog-paesa-es_default

volumes:
  data:
    name: blog-paesa-es_data
